# -*- coding: utf-8 -*-
"""JSS3/2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12ekgPmvECOU7B1l-q3b4mdODqTrxQbll
"""

#LOGISTIC REGRESSION(CLASSIFIER)-SUPERVISED LERANING TECHNIQUE
#1.TAKE DATA AND CREATE DATAFRAME
import pandas as pd
af=pd.read_csv('/content/IRIS.csv')
af

x=af.iloc[:,0:4].values
x

y=af.iloc[:,-1].values
y

#Train test split
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,random_state=0)

print(x.shape)
print(x_train.shape)
print(x_test.shape)

#Apply Regressor/classsifier/clusterer
from sklearn.linear_model import LogisticRegression
model=LogisticRegression()

#8 Fitting the model
model.fit(x_train,y_train)

#9 predict the output/Predictor variable
y_pred=model.predict(x_test)#using the input testing values we predict the output
y_pred

y_test

#INDIVUAL PREDICTION
model.predict([[5.2,3.5,1.4,.2]])

#to check accuracy
from sklearn.metrics import accuracy_score
accuracy_score(y_pred,y_test)*100

model.predict([[6.7,3.0,5.2,2.3]])

