# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1V6yiAacfiOP2SzTSkqA-ssH5c3e2R2wo

*italicised text*
"""

import pandas as pd
af=pd.DataFrame()
af=pd.read_csv('https://raw.githubusercontent.com/ameenmanna8824/DATASETS/main/laptops.csv',encoding='latin-1')
af

af.info

af.shape

af.size

#to check the null value
af.isnull().sum()

af.drop(columns='Unnamed: 0')

af

af['Ram']=af['Ram'].str.replace('GB','')

af

af.info()

#Converting the datatype of tam column from string to Integer
af['Ram']=af['Ram'].astype('int64')

af.info()

af['Weight']=af['Weight'].str.replace('kg','')

af

af['Weight']=af['Weight'].astype('float64')

af.info()

af

af=af.drop(columns='weight')

#VISUALIZATION
#distibution plot
import seaborn as sns
sns.distplot(af['Price_euros'])

#I want to know,which brand of laptops are more in number
af['Company'].value_counts().plot(kind='bar')

#I want to find out the most expensive brand of laptop
import matplotlib.pyplot as plt
sns.barplot(x=af['Company'],y= af['Price_euros'])
plt.xticks(rotation ='vertical')

#NOW I want to know that which type of laptop is most available one
af['TypeName'].value_counts().plot(kind='bar')

#Based on Typename,I want to know which type is the most expensive one
sns.barplot(x=af['TypeName'],y=af['Price_euros'])
plt.xticks(rotation ='vertical')

#I want to know the most common scrren size of the laptops available
sns.distplot(af['Inches'])

#NOW I want to find out the most common configuration of Ram
af['Ram'].value_counts().plot(kind='bar')

#Now I want to know which configuration of Ram is the most expensive one
sns.barplot(x=af['Ram'],y=af['Price_euros'])
plt.xticks(rotation ='vertical')

#NOw I want to know all the possible storage configuration ever available in af
plt.figure(figsize=(12,6))
af['Memory'].value_counts().plot(kind='bar')

