# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1V6yiAacfiOP2SzTSkqA-ssH5c3e2R2wo

*italicised text*
"""



#EDA -TITANIC DATASET
import pandas as pd
of=pd.DataFrame()
of=pd.read_csv('/content/train.csv')
of

of.info()

of.shape

of.size

of.columns

of.describe()

of.isnull().sum()#decribes if it has null value or not

#I want to find out the count of unique elements in each column
#VISUALIZATION using Seasborn(a visualization library)
import seaborn as sns
sns.countplot (x ='Survived',data=of)

of['Survived'].value_counts()

sns.countplot(x='Sex',data = of)

fsize2= of.groupby('Sex',sort= 'false').size()
fsize2

fsize2= of.groupby(['Survived','Sex'],sort= 'false').size()
fsize2

import numpy as np
survived_m=np.sum((of['Sex']=='male')&(of['Survived']==1))
survived_m

young=np.sum((of['Age']>=0)&(of['Age']<20))
adult=np.sum((of['Age']>=20)&(of['Age']<40))
midage=np.sum((of['Age']>=40)&(of['Age']<60))
old=np.sum((of['Age']>=60)&(of['Age']<100))
print(young)
print(adult)
print(midage)
print(old)

adult

midage

old

young

#I want to know the youngest person aboard titanic
np.min(of['Age'])

#I want to know the oldest person abroad titanic
np.max(of['Age'])

#didtribution plot
sns.distplot(of['Age'])



